disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- nesting
- function_parameter_count

opt_in_rules: # some rules are only opt-in
- control_statement
- empty_count
- empty_string
- trailing_newline
- colon
- comma

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- Carthage

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting

force_try:
 severity: warning # explicitly. Give warning only for force try

line_length:
 ignores_comments: true
 warning: 160
 error: 200

type_body_length:
- 300 # warning
- 500 # error

cyclomatic_complexity:
- 15 # warning
- 20 # error

# or they can set both explicitly
file_length:
- 1000 # warning
- 1500 # error

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
- 3
- 4

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
 min_length: 4 # only warning
 max_length: # warning and error
  warning: 30
  error: 35

reporter: "xcode"
