# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'SimpleCamera' do
    pod 'PureLayout'
    pod 'SwiftLint'
    pod 'Player'
    pod 'Floaty'
    pod 'OpenCV2'
    pod 'Parse'

    target 'SimpleCameraTests' do
        inherit! :search_paths
    end
    
    target 'SimpleCameraUITests' do
        inherit! :search_paths
    end
end
