# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'SimpleCamera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'PureLayout'
    pod 'SwiftLint'
    pod 'Player', '~> 0.7.0'
    pod 'Floaty', '~> 3.0.0' # Use version 4.0.0 for Swift 4.0
  # Pods for SimpleCamera

  target 'SimpleCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleCameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
